# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre estado')),
                ('estado', models.BooleanField(verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGrupo', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10, verbose_name='Estado Grupo')),
                ('propietarios', models.CharField(max_length=200, null=True, verbose_name='Propietarios')),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso_name', models.CharField(max_length=100, unique=True, verbose_name='Permiso')),
                ('permiso_uri', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='uri')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permiso_usuario', to='app.Permisos')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField(unique=True, verbose_name='N\xfamero de C\xe9dula')),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombre Taquillero')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos Taquillero')),
                ('correo', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Correo Electronico')),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rifa', models.CharField(max_length=50, unique=True, verbose_name='Nombre Rifa')),
            ],
        ),
        migrations.CreateModel(
            name='RifaLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(verbose_name='Posici\xf3n')),
                ('image', models.ImageField(upload_to='images/animales')),
                ('nombre_imagen', models.CharField(max_length=30, verbose_name='Nombre Imagen')),
                ('rifa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rifa', to='app.Rifa')),
            ],
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sorteo', models.DateField(null=True)),
                ('numero_ganador', models.IntegerField()),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rifa')),
            ],
        ),
        migrations.CreateModel(
            name='SorteoHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_sorteo', models.TimeField()),
                ('rifa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorteo_horas', to='app.Rifa')),
            ],
        ),
        migrations.CreateModel(
            name='Taquilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='app.Grupo')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_cobro', models.CharField(max_length=8, verbose_name='Serial cobro')),
                ('estado', models.CharField(choices=[('1', 'EN JUEGO'), ('2', 'GANADO'), ('3', 'PERDIDO'), ('4', 'PAGADO'), ('5', 'CADUCADO')], default='EN JUEGO', max_length=10, verbose_name='Estado Venta')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('time', models.TimeField(null=True, verbose_name='Hora')),
                ('total_apostado', models.IntegerField(default=0)),
                ('total_ganancia', models.IntegerField(default=0)),
                ('fecha_pago', models.DateTimeField(null=True)),
                ('taquilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taquila', to='app.Taquilla')),
                ('usuarioPagador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pagador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_apuesta', models.IntegerField()),
                ('estado', models.CharField(choices=[('1', 'EN JUEGO'), ('2', 'GANADO'), ('3', 'PERDIDO'), ('4', 'PAGADO'), ('5', 'CADUCADO')], default='EN JUEGO', max_length=10, verbose_name='Estado Venta')),
                ('detalle_rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_rifa', to='app.RifaLista')),
                ('sorteo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorteo', to='app.Sorteo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='app.Venta')),
            ],
        ),
        migrations.AddField(
            model_name='sorteo',
            name='sorteoHoras',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorteo_horas', to='app.SorteoHora'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='grupos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grupos', to='app.Grupo'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_administrador', to='app.Persona'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
