# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_testcrontab'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronTabLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='TestCronTab',
        ),
    ]
