# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180209_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='usuarioPagador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pagador', to=settings.AUTH_USER_MODEL),
        ),
    ]
