# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180212_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Permiso'),
        ),
    ]
