# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ventadetalle_tipo_apuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventadetalle',
            name='detalle_rifa',
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='numeros',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numeros apostados'),
        ),
    ]
