# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180302_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='ganancia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
